/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Berths */
        get: operations["list_berths"];
        put?: never;
        /** Create Berth */
        post: operations["create_berth"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/berths/{berth_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Berth */
        patch: operations["update_berth"];
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Organizations */
        get: operations["list_organizations"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organization */
        get: operations["get_organization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Organization */
        patch: operations["update_organization"];
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Contacts */
        get: operations["list_contacts"];
        put?: never;
        /** Create Contact */
        post: operations["create_contact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/{contact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Contact */
        get: operations["get_contact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Contact */
        patch: operations["update_contact"];
        trace?: never;
    };
    "/api/vessels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vessels */
        get: operations["list_vessels"];
        put?: never;
        /** Create Vessel */
        post: operations["create_vessel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vessels/{vessel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vessel */
        get: operations["get_vessel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Vessel */
        patch: operations["update_vessel"];
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Bookings */
        get: operations["list_bookings"];
        put?: never;
        /** Create Booking Endpoint */
        post: operations["create_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Bookings Csv */
        get: operations["export_bookings_csv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Booking */
        get: operations["get_booking"];
        put?: never;
        post?: never;
        /** Delete Booking Endpoint */
        delete: operations["delete_booking"];
        options?: never;
        head?: never;
        /** Update Booking Endpoint */
        patch: operations["update_booking"];
        trace?: never;
    };
    "/api/bookings/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Booking Endpoint */
        post: operations["validate_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{booking_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking Endpoint */
        post: operations["cancel_booking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Availability */
        get: operations["check_availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventRead */
        AuditEventRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** BerthAvailability */
        BerthAvailability: {
            /** Berth Id */
            berth_id: number;
            /** Berth Name */
            berth_name: string;
            /** Length Ft */
            length_ft: number | null;
            /** Fits */
            fits: boolean;
            /** Fit Reason */
            fit_reason: string;
            /** Free */
            free: boolean;
            /** Spare Ft */
            spare_ft?: number | null;
            /**
             * Conflicts
             * @default []
             */
            conflicts: components["schemas"]["ConflictingBooking"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["Issue"][];
        };
        /** BerthCreate */
        BerthCreate: {
            /** Name */
            name: string;
            /** Length Ft */
            length_ft?: number | null;
            /** Max Draft Ft */
            max_draft_ft?: number | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Sort Order
             * @default 0
             */
            sort_order: number;
            /** Notes */
            notes?: string | null;
        };
        /** BerthRead */
        BerthRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Length Ft */
            length_ft: number | null;
            /** Max Draft Ft */
            max_draft_ft: number | null;
            /** Is Active */
            is_active: boolean;
            /** Sort Order */
            sort_order: number;
            /** Notes */
            notes: string | null;
        };
        /** BerthUpdate */
        BerthUpdate: {
            /** Name */
            name?: string | null;
            /** Length Ft */
            length_ft?: number | null;
            /** Max Draft Ft */
            max_draft_ft?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Sort Order */
            sort_order?: number | null;
            /** Notes */
            notes?: string | null;
        };
        /** BookingCreate */
        BookingCreate: {
            /** Berth Id */
            berth_id: number;
            kind: components["schemas"]["BookingKind"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** @default confirmed */
            status: components["schemas"]["BookingStatus"];
            /** Vessel Id */
            vessel_id?: number | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** BookingDetail */
        BookingDetail: {
            /** Id */
            id: number;
            /** Berth Id */
            berth_id: number;
            /** Berth Name */
            berth_name: string;
            kind: components["schemas"]["BookingKind"];
            /** Vessel Id */
            vessel_id: number | null;
            /** Vessel Name */
            vessel_name: string | null;
            /** Vessel Loa Ft */
            vessel_loa_ft: number | null;
            /** Title */
            title: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            status: components["schemas"]["BookingStatus"];
            /** Notes */
            notes: string | null;
            source: components["schemas"]["BookingSource"];
            /** Source Ref */
            source_ref: string | null;
            /** Created By */
            created_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Audit History
             * @default []
             */
            audit_history: components["schemas"]["AuditEventRead"][];
        };
        /**
         * BookingKind
         * @enum {string}
         */
        BookingKind: "vessel" | "event" | "closure";
        /** BookingRead */
        BookingRead: {
            /** Id */
            id: number;
            /** Berth Id */
            berth_id: number;
            /** Berth Name */
            berth_name: string;
            kind: components["schemas"]["BookingKind"];
            /** Vessel Id */
            vessel_id: number | null;
            /** Vessel Name */
            vessel_name: string | null;
            /** Vessel Loa Ft */
            vessel_loa_ft: number | null;
            /** Title */
            title: string | null;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            status: components["schemas"]["BookingStatus"];
            /** Notes */
            notes: string | null;
            source: components["schemas"]["BookingSource"];
            /** Source Ref */
            source_ref: string | null;
            /** Created By */
            created_by: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * BookingSource
         * @enum {string}
         */
        BookingSource: "app" | "import";
        /**
         * BookingStatus
         * @enum {string}
         */
        BookingStatus: "tentative" | "confirmed" | "cancelled" | "legacy_conflict";
        /**
         * BookingUpdate
         * @description Partial update. The router merges these onto the booking's current
         *     values before calling the booking rules, per DECISIONS.md.
         */
        BookingUpdate: {
            /** Berth Id */
            berth_id?: number | null;
            kind?: components["schemas"]["BookingKind"] | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            status?: components["schemas"]["BookingStatus"] | null;
            /** Vessel Id */
            vessel_id?: number | null;
            /** Title */
            title?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** BookingValidateRequest */
        BookingValidateRequest: {
            /** Berth Id */
            berth_id: number;
            kind: components["schemas"]["BookingKind"];
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** @default confirmed */
            status: components["schemas"]["BookingStatus"];
            /** Vessel Id */
            vessel_id?: number | null;
            /** Title */
            title?: string | null;
            /** Booking Id */
            booking_id?: number | null;
        };
        /** ConflictingBooking */
        ConflictingBooking: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
        };
        /** ContactCreate */
        ContactCreate: {
            /** Name */
            name: string;
            /** Organization Id */
            organization_id?: number | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ContactRead */
        ContactRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: number | null;
            /** Phone */
            phone: string | null;
            /** Email */
            email: string | null;
            /** Notes */
            notes: string | null;
        };
        /** ContactUpdate */
        ContactUpdate: {
            /** Name */
            name?: string | null;
            /** Organization Id */
            organization_id?: number | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Issue */
        Issue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Field */
            field?: string | null;
            /** Related Booking Id */
            related_booking_id?: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OrganizationCreate */
        OrganizationCreate: {
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
        };
        /** OrganizationRead */
        OrganizationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Notes */
            notes: string | null;
        };
        /** OrganizationUpdate */
        OrganizationUpdate: {
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "staff" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Ok */
            ok: boolean;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["Issue"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["Issue"][];
        };
        /** VesselBookingSummary */
        VesselBookingSummary: {
            /** Id */
            id: number;
            /** Berth Id */
            berth_id: number;
            /** Berth Name */
            berth_name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Status */
            status: string;
        };
        /** VesselCreate */
        VesselCreate: {
            /** Name */
            name: string;
            /** Type Prefix */
            type_prefix?: string | null;
            /** Loa Ft */
            loa_ft?: number | null;
            /** Draft Ft */
            draft_ft?: number | null;
            /** Organization Id */
            organization_id?: number | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** VesselDetail */
        VesselDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type Prefix */
            type_prefix: string | null;
            /** Normalized Key */
            normalized_key: string;
            /** Loa Ft */
            loa_ft: number | null;
            /** Draft Ft */
            draft_ft: number | null;
            /** Organization Id */
            organization_id: number | null;
            /** Is Active */
            is_active: boolean;
            /** Notes */
            notes: string | null;
            /**
             * Contacts
             * @default []
             */
            contacts: components["schemas"]["ContactRead"][];
            /**
             * Upcoming Bookings
             * @default []
             */
            upcoming_bookings: components["schemas"]["VesselBookingSummary"][];
            /**
             * Past Bookings
             * @default []
             */
            past_bookings: components["schemas"]["VesselBookingSummary"][];
        };
        /** VesselRead */
        VesselRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Type Prefix */
            type_prefix: string | null;
            /** Normalized Key */
            normalized_key: string;
            /** Loa Ft */
            loa_ft: number | null;
            /** Draft Ft */
            draft_ft: number | null;
            /** Organization Id */
            organization_id: number | null;
            /** Is Active */
            is_active: boolean;
            /** Notes */
            notes: string | null;
        };
        /** VesselUpdate */
        VesselUpdate: {
            /** Name */
            name?: string | null;
            /** Type Prefix */
            type_prefix?: string | null;
            /** Loa Ft */
            loa_ft?: number | null;
            /** Draft Ft */
            draft_ft?: number | null;
            /** Organization Id */
            organization_id?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_berths: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_berth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BerthCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_berth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                berth_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BerthUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_organizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"][];
                };
            };
        };
    };
    create_organization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_contacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"][];
                };
            };
        };
    };
    create_contact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_contact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_contact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contact_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContactUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vessels: {
        parameters: {
            query?: {
                q?: string | null;
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vessel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VesselCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vessel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_vessel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vessel_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VesselUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VesselRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_bookings: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                berth_id?: number | null;
                vessel_id?: number | null;
                kind?: components["schemas"]["BookingKind"] | null;
                status?: components["schemas"]["BookingStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_booking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_bookings_csv: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                berth_id?: number | null;
                vessel_id?: number | null;
                kind?: components["schemas"]["BookingKind"] | null;
                status?: components["schemas"]["BookingStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_booking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                booking_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_availability: {
        parameters: {
            query: {
                start: string;
                end: string;
                vessel_id?: number | null;
                loa_ft?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BerthAvailability"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
